"""
Reports generated by Ratio Engine
"""

from pathlib import Path

import pandas as pd

OUTPUT = Path("output")
OUTPUT.mkdir(exist_ok=True)


def save_capital_allocation(df):

    columns = [
        "company_id",
        "year",
        "capital_allocation"
    ]

    df[columns].to_csv(
        OUTPUT / "capital_allocation.csv",
        index=False
    )

    print(
        "capital_allocation.csv created"
    )


def save_ratio_edge_cases(edge_cases):

    path = OUTPUT / "ratio_edge_cases.log"

    with open(
        path,
        "w",
        encoding="utf-8"
    ) as file:

        for row in edge_cases:

            file.write(
                row + "\n"
            )

    print(
        "ratio_edge_cases.log created"
    )